#!/usr/bin/env node
/**
 * TDS Design Import -> EBC
 *
 * Reads a TDS .kmz (or an already-extracted doc.kml) and reports, or emits, the
 * design the EBC needs. Node 54 was the first project validated through this
 * path; nothing here is specific to it.
 *
 *   node tools/import_tds_kmz.mjs <file.kmz|doc.kml>
 *   node tools/import_tds_kmz.mjs <file> --node 1635CA --pon P0002
 *   node tools/import_tds_kmz.mjs <file> --node 1635CA --pon P0002 --emit > out.mjs
 *   node tools/import_tds_kmz.mjs <file> --json
 *
 * --emit writes a frozen design module in the same shape as
 * services/ebc/node54TdsDesign.mjs, so a new project becomes a reviewable file
 * rather than a runtime parse of a 20 MB KML in the browser.
 *
 * This tool never fabricates engineering values. If the export carries no
 * optical loss, it says so and emits nothing for loss.
 */

import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { extractTdsDesign, tdsLegToEbcLeg } from "../services/ebc/tdsKmzImport.mjs";

function readKml(path){
  if (/\.kml$/i.test(path)) return readFileSync(path, "utf8");
  if (!/\.kmz$/i.test(path)) throw new Error("Expected a .kmz or .kml file, received: " + path);
  // A KMZ is a zip. Rather than take a dependency, shell out to the platform
  // unzip; if that is unavailable the caller can extract doc.kml themselves.
  try {
    return execFileSync("unzip", ["-p", path, "doc.kml"], { encoding: "utf8", maxBuffer: 512 * 1024 * 1024 });
  } catch (error){
    throw new Error("Could not extract doc.kml from " + path + ". Unzip it manually and pass doc.kml instead. (" + error.message + ")");
  }
}

function parseArgs(argv){
  const args = { file: "", node: "", pon: "", project: "", emit: false, json: false };
  for (let i = 0; i < argv.length; i += 1){
    const token = argv[i];
    if (token === "--node") args.node = argv[++i] || "";
    else if (token === "--pon") args.pon = argv[++i] || "";
    else if (token === "--project") args.project = argv[++i] || "";
    else if (token === "--emit") args.emit = true;
    else if (token === "--json") args.json = true;
    else if (!args.file) args.file = token;
  }
  return args;
}

const args = parseArgs(process.argv.slice(2));
if (!args.file){
  console.error("usage: node tools/import_tds_kmz.mjs <file.kmz|doc.kml> [--node X] [--pon Y] [--project Z] [--emit|--json]");
  process.exit(2);
}

const design = extractTdsDesign(readKml(args.file), { node: args.node, pon: args.pon, project: args.project });

if (args.json){
  process.stdout.write(JSON.stringify(design, null, 2));
  process.exit(0);
}

if (args.emit){
  process.stdout.write(emitModule(design, args));
  process.exit(0);
}

// --- Human summary --------------------------------------------------------
const line = (label, value) => console.log(label.padEnd(30) + value);
console.log("TDS DESIGN IMPORT — " + args.file);
console.log("=".repeat(72));
line("Placemarks parsed", design.placemarkCount);
line("Projects", design.projects.join(", ") || "(none)");
line("Node/PON combinations", design.pons.length);
line("Tap devices", design.devices.length);
line("Legs", design.legs.length);
line("Catalogue descriptions", design.catalogueDescriptions.length);
console.log("");
console.log("OPTICAL LOSS IN THIS EXPORT");
line("  Field", design.lossFieldName);
line("  Contains usable loss", design.containsInsertionLoss ? "YES" : "NO");
for (const entry of design.lossFieldSummary) line("  value " + entry.value, entry.count + " device(s)");
if (!design.containsInsertionLoss){
  console.log("  -> No insertion loss present. PCOT specifications remain UNVERIFIED.");
}
console.log("");
console.log("LEGS");
for (const leg of design.legs){
  const head = leg.head ? "NP" + (leg.head.np || "?") + "/CP" + leg.head.cp : "unidentified feed";
  console.log("  " + leg.key.padEnd(24) + " head " + head.padEnd(20) + " " +
    leg.nodes.map((n) => n.position + ":NP" + (n.np || "?") + "(" + n.tapRatio + (n.spanFeetFromPrevious === null || n.spanFeetFromPrevious === undefined ? "" : ", " + n.spanFeetFromPrevious + "ft") + ")").join(" -> "));
}
if (design.warnings.length){
  console.log("");
  console.log("WARNINGS (" + design.warnings.length + ")");
  for (const warning of design.warnings) console.log("  - " + warning);
}
console.log("");
console.log("Engineering constants this export does NOT supply, and the EBC will");
console.log("therefore keep asking for: launch power, receiver minimum/maximum,");
console.log("engineering reserve, fiber attenuation, splice loss, connector loss,");
console.log("PCOT insertion loss.");

function emitModule(extracted, options){
  const legs = extracted.legs;
  const parts = extracted.catalogueDescriptions;
  const out = [];
  out.push("/**");
  out.push(" * EBC — TDS design record, generated by tools/import_tds_kmz.mjs.");
  out.push(" * Source file: " + options.file);
  out.push(" * Filters: " + JSON.stringify({ node: options.node, pon: options.pon, project: options.project }));
  out.push(" *");
  out.push(" * Cascade order is the TDS Splitter Path position. Span footage is the TDS");
  out.push(" * cable placement quantity, which is design footage and not a measured");
  out.push(" * sheath length. This export contains " + (extracted.containsInsertionLoss ? "optical loss values." : "NO optical loss values."));
  out.push(" * Do not hand-edit; re-run the importer against a newer export.");
  out.push(" */");
  out.push("");
  out.push("export const TDS_SOURCE = Object.freeze({");
  out.push("  file: " + JSON.stringify(options.file.split(/[\\/]/).pop()) + ",");
  out.push("  projects: " + JSON.stringify(extracted.projects) + ",");
  out.push("  containsInsertionLoss: " + extracted.containsInsertionLoss + ",");
  out.push("  lossFieldName: " + JSON.stringify(extracted.lossFieldName) + ",");
  out.push("  catalogueDescriptions: Object.freeze(" + JSON.stringify(parts) + "),");
  out.push("});");
  out.push("");
  out.push("export const TDS_LEGS = Object.freeze({");
  for (const leg of legs){
    out.push("  " + JSON.stringify(leg.key) + ": Object.freeze({");
    out.push("    project: " + JSON.stringify(leg.project) + ", node: " + JSON.stringify(leg.node) + ", pon: " + JSON.stringify(leg.pon) + ", branch: " + JSON.stringify(leg.branch) + ",");
    out.push("    head: " + (leg.head ? JSON.stringify(leg.head) : "null") + ",");
    out.push("    nodes: Object.freeze([");
    for (const device of leg.nodes){
      out.push("      Object.freeze(" + JSON.stringify({
        position: device.position, np: device.np, cp: device.cp, ratio: device.tapRatio,
        materialUnit: device.catalogueDescription, splitterRatio: device.splitterRatio,
        spanFeetFromPrevious: device.spanFeetFromPrevious ?? null,
        lat: device.coords ? device.coords.lat : null, lng: device.coords ? device.coords.lng : null,
      }) + "),");
    }
    out.push("    ]),");
    out.push("  }),");
  }
  out.push("});");
  out.push("");
  return out.join("\n");
}
